# Generated by Django 5.2.8 on 2026-04-18 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cardio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=20)),
                ('height', models.DecimalField(decimal_places=2, max_digits=20)),
                ('chest', models.DecimalField(decimal_places=2, max_digits=20)),
                ('waist', models.DecimalField(decimal_places=2, max_digits=20)),
                ('hips', models.DecimalField(decimal_places=2, max_digits=20)),
                ('thighs', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='WeightTraining',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='SessionCardio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DecimalField(decimal_places=2, max_digits=20)),
                ('level', models.PositiveIntegerField()),
                ('incline', models.PositiveIntegerField()),
                ('cardio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymsisAPI.cardio')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymsisAPI.session')),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='gymsisAPI.user'),
        ),
        migrations.CreateModel(
            name='SessionTraining',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=20)),
                ('reps', models.PositiveIntegerField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymsisAPI.session')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymsisAPI.weighttraining')),
            ],
        ),
    ]
